services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "6644:6644"
    env_file:
      - ./api/.env
    container_name: hcgateway_api
    restart: always
    volumes:
      - ./api/service-account.json:/app/service-account.json
